// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
)

// Injectors from wire_inject.go:

//go:generate wire
func initializeApp(ctx context.Context, cfg *config) (*App, error) {
	bootstrapMysqlDatabases, err := provideMySQLDatabases(ctx, cfg)
	if err != nil {
		return nil, err
	}
	clientRepository := provideClientRepository(bootstrapMysqlDatabases)
	sessionRepository := provideSessionRepository(cfg, bootstrapMysqlDatabases)
	client, err := provideRedis(ctx, cfg)
	if err != nil {
		return nil, err
	}
	keyBuilder := provideKeyBuilder(cfg)
	sessionCacheRepository := provideSessionCacheRepository(client, keyBuilder)
	authorizationCodeRepository := provideAuthorizationCodeRepository(bootstrapMysqlDatabases)
	consentRepository := provideConsentRepository(bootstrapMysqlDatabases)
	service := provideAuthzService(clientRepository, sessionRepository, sessionCacheRepository, authorizationCodeRepository, consentRepository)
	manager := provideConsentManager(clientRepository, sessionRepository, sessionCacheRepository, consentRepository)
	userRepository := provideUserRepository(bootstrapMysqlDatabases)
	passwordVerifier := providePasswordVerifier()
	rateLimitRepository := provideRateLimitRepository(client, keyBuilder)
	registerService := provideRegisterService(userRepository, passwordVerifier, rateLimitRepository)
	registrar := provideRegistrar(registerService)
	passwordResetter := providePasswordResetter(registerService)
	accountUnlocker := provideAccountUnlocker(registerService)
	clientService := provideClientService(clientRepository, passwordVerifier)
	creator := provideClientCreator(clientService)
	clientRegistrar := provideClientRegistrar(clientService)
	postLogoutRegistrar := provideClientPostLogoutRegistrar(clientService)
	logoutRedirectValidator := provideLogoutRedirectValidator(clientService)
	mfaRepository := provideMFARepository(client, keyBuilder)
	replayProtectionRepository := provideReplayProtectionRepository(client, keyBuilder)
	oidcProvider := provideFederatedOIDCProvider(cfg, replayProtectionRepository)
	authnRegistry := provideAuthnRegistry(userRepository, passwordVerifier, oidcProvider)
	secretCodec, err := provideSecretCodec(cfg)
	if err != nil {
		return nil, err
	}
	totpRepository := provideTOTPRepository(bootstrapMysqlDatabases, secretCodec)
	totpProvider := provideTOTPProvider()
	passkeyCredentialRepository := providePasskeyRepository(bootstrapMysqlDatabases)
	passkeyProvider, err := providePasskeyProvider(cfg)
	if err != nil {
		return nil, err
	}
	authenticator := provideAuthnService(cfg, userRepository, sessionRepository, sessionCacheRepository, rateLimitRepository, mfaRepository, authnRegistry, totpRepository, totpProvider, passkeyCredentialRepository, passkeyProvider)
	tokenRepository := provideTokenStore(cfg, bootstrapMysqlDatabases)
	tokenCacheRepository := provideTokenCacheRepository(client, keyBuilder)
	sessionManager := provideSessionManager(sessionRepository, sessionCacheRepository, tokenRepository, tokenCacheRepository)
	operatorRoleRepository := provideOperatorRoleRepository(bootstrapMysqlDatabases)
	rbacManager := provideRBACManager(operatorRoleRepository, userRepository)
	jwkKeyRepository := provideJWKRepository(bootstrapMysqlDatabases)
	rotationConfig := provideRotationConfig(cfg)
	keySyncBroadcaster := provideKeySyncBroadcaster(client, cfg)
	keyManager, err := provideKeyManager(ctx, cfg, jwkKeyRepository, rotationConfig, keySyncBroadcaster)
	if err != nil {
		return nil, err
	}
	keysManager := provideKeysManager(jwkKeyRepository, keyManager, rotationConfig, keySyncBroadcaster)
	shortURLRepository := provideShortURLRepository(bootstrapMysqlDatabases)
	shorturlManager := provideShortURLManager(shortURLRepository)
	auditEventRepository := provideAuditStore(bootstrapMysqlDatabases)
	repositoryAuditEventRepository, err := provideAuditEventRepository(client, cfg, keyBuilder, auditEventRepository)
	if err != nil {
		return nil, err
	}
	clientAuthRegistry := provideClientAuthRegistry(passwordVerifier)
	clientauthAuthenticator := provideClientAuthenticator(clientRepository, clientAuthRegistry)
	repositoryTokenRepository := provideTokenRepository(tokenRepository)
	deviceCodeRepository := provideDeviceCodeRepository(client, keyBuilder)
	jwtService := provideJWTService(keyManager)
	tokenService := provideTokenService(cfg, authorizationCodeRepository, clientRepository, userRepository, repositoryTokenRepository, tokenCacheRepository, deviceCodeRepository, passwordVerifier, jwtService)
	grantRegistry := provideGrantRegistry(tokenService)
	deviceService := provideDeviceService(clientRepository, deviceCodeRepository, sessionRepository, sessionCacheRepository)
	mfaManager := provideMFAService(cfg, sessionRepository, sessionCacheRepository, userRepository, totpRepository, mfaRepository, totpProvider)
	passkeyManager := providePasskeyService(cfg, sessionRepository, sessionCacheRepository, userRepository, passkeyCredentialRepository, mfaRepository, passkeyProvider)
	oidcService := provideOIDCService(cfg, userRepository, repositoryTokenRepository, tokenCacheRepository, jwtService, keyManager)
	authMiddleware := provideAuthMiddleware(cfg, tokenCacheRepository, jwtService)
	sessionPermissionMiddleware := provideAdminMiddleware(sessionRepository, sessionCacheRepository, userRepository)
	handler := provideRouter(cfg, service, manager, registrar, passwordResetter, accountUnlocker, userRepository, creator, clientRegistrar, postLogoutRegistrar, logoutRedirectValidator, authenticator, oidcProvider, sessionManager, rbacManager, keysManager, shorturlManager, repositoryAuditEventRepository, clientauthAuthenticator, grantRegistry, deviceService, mfaManager, passkeyManager, oidcService, authMiddleware, sessionPermissionMiddleware)
	app := provideApp(handler)
	return app, nil
}
